<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Viewing the Jobs Table</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .header {
            background-color: #28a745;
            color: white;
            text-align: center;
            padding: 20px;
            position: relative;
        }
        .header img {
            position: absolute;
            left: 20px;
            top: 50%;
            transform: translateY(-50%);
            height: 100px; /* Increased logo size */
        }
        .header .title {
            font-size: 32px; /* Increased message size */
            margin: 0;
        }
        .sub-header {
            background-color: #218838;
            height: 20px;
        }
        table {
            width: 80%;
            margin: 40px auto; /* Centering the table and adding margin */
            border-collapse: collapse;
            box-shadow: 0 2px 3px rgba(0,0,0,0.1);
            background: #fff;
            border: 1px solid #ddd; /* Adding border to the table */
            border-radius: 8px; /* Adding border radius */
            overflow: hidden; /* Ensuring border radius applies to table content */
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #28a745; /* Setting header row color */
            color: white;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
        tr:last-child td {
            border-bottom: none;
        }
    </style>
</head>
<body>
    <div class="header">
        <img src="WVAlogo.svg" alt="Logo">
        <div class="title">Completed Jobs</div>
    </div>
    <div class="sub-header"></div>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Location</th>
            <th>Description</th>
            <th>Completed</th>
        </tr>
        <?php
        // Database connection variables for the database on your web server
        $servername = "localhost"; // You can leave server name as localhost, as the database is on the same server as apache.
        $username = "job_management_username_2024";
        $password = "job_management_password_2024";
        $database = "job_management_name_2024";

        // We start a try and catch block to attempt to connect to our database and run the query. If it fails, we see the error/exception generated by the catch
        try {
            $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password); // Building a new PDO connection object
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); // Set the PDO error mode to exception

            // Selecting multiple rows from a MySQL database using the PDO::query function.
            // Filtering the data where completed is 'yes' and sorting by the ID field, limiting the results to the last 50 for the purpose of this example
            $sql = "SELECT * FROM jobs_table WHERE completed = 'yes' ORDER BY id DESC LIMIT 50";

            // For each result that we return, loop through the result and perform the echo statements.
            // Data will be formatted into a table
            // $row is an array with the fields for each record returned from the SELECT
            foreach ($conn->query($sql, PDO::FETCH_ASSOC) as $row) {
                echo '<tr>';
                echo '<td>' . htmlspecialchars($row['first_name']) . '</td>';
                echo '<td>' . htmlspecialchars($row['last_name']) . '</td>';
                echo '<td>' . htmlspecialchars($row['email']) . '</td>';
                echo '<td>' . htmlspecialchars($row['location']) . '</td>';
                echo '<td>' . htmlspecialchars($row['description']) . '</td>';
                echo '<td>' . htmlspecialchars($row['completed']) . '</td>';
                echo '</tr>';
            }
        } catch (PDOException $e) {
            echo "<tr><td colspan='6'>Error: " . htmlspecialchars($e->getMessage()) . "</td></tr>"; // If we are not successful we will see an error
        }
        ?>
    </table>
</body>
</html>
